---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-deploy
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "image updated to v1.0"
spec:
  minReadySeconds: 1
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: deploysample
          image: shivasomanath/practice:1.0
          ports:
            - name: webport
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: webport
            failureThreshold: 3
            periodSeconds: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: webport
            failureThreshold: 2
            periodSeconds: 2
            successThreshold: 1
      