apiVersion: batch/v1
kind: Job
metadata:
  name: jobspec
spec:
  template:
    metadata:
      name: jobpod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Never
