apiVersion: v1
kind: Pod
metadata:
  name: mysql-vol
  labels:
    app: mysql
    layer: db
spec:
  containers:
  - name: mysql
    image: mysql:8
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: test-volume
      mountPath: /var/lib/mysql
  volumes:
  - name: test-volume
    emptyDir:
      sizeLimit: 100Mi

# kubectl get sc
