---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod-lable1
  labels:
    app: nginx
    env: dev
    releases: v1
spec: 
  containers:
    - name: webserver
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod-lable2
  labels:
    app: nginx
    env: qa
    releases: v1
spec: 
  containers:
    - name: app
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod-lable3
  labels:
    app: nginx
    env: uat
    releases: v1
spec: 
  containers:
    - name: mob
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP
