apiVersion: v1	
kind: Pod
metadata:
  name: jenkins
spec:
  activeDeadlineSeconds: 5
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
  ephemeralContainers:
    - name: ephem
      image: busybox
      command:
        - 'sh' 
        - '-c' 
        - "until nslookup nginx-svc.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"
