apiVersion: v1 
kind: Pod
metadata:
  name: cm-s-demo
  labels:
    app: demo
spec:
  containers:
    - name: exp
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: userinfo-cm
        - secretRef:
            name: userinfo-secret