apiVersion: v1 
kind: Pod
metadata:
  name: cm-s-demo
  labels:
    app: demo
spec:
  containers:
    - name: exp
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: username-vol
          mountPath: /creds/username
        - name: password-vol
          mountPath: /creds/password
  volumes:
    - name: username-vol
      configMap: 
        name: userinfo-cm
    - name: password-vol
      secret:
        secretName: userinfo-secret