---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-file
spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
      volumeMounts:
        - name: dummy
          mountPath: /tmp/dummy
  volumes:
    - name: dummy
      configMap:
        name: dummy-cm