apiVersion: v1
kind: Pod
metadata:
  name: nginxn2
  labels:
    app: nginx
    component: web
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
