apiVersion: v1
kind: Pod
metadata:
  name: lablenginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.23
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
