apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-nodeportrs
  labels:
    app: jenkins
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
          protocol: TCP


