apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    layer: web
    version: "1.23"
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - name: nginx-svc
    port: 80
    targetPort: 80
    protocol: TCP
